stages:
    - build
    - test
    - release
    - deploy

variables:
    TAG_LATEST_EVAC_SIM: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/evac-sim:latest
    TAG_COMMIT_EVAC_SIM: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/evac-sim:$CI_COMMIT_SHORT_SHA 

build-job:
    stage: build
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
    stage: test
    script:
        - echo "This job tests something"

test-job2:
    stage: test
    script:
        - echo "This job tests something too!"

release:
    image: docker:latest
    stage: release
    services:
        - docker:dind
    script:
        - docker build -t $TAG_COMMIT_EVAC_SIM -t $TAG_LATEST_EVAC_SIM .
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker push $TAG_COMMIT_EVAC_SIM
        - docker push $TAG_LATEST_EVAC_SIM
        

deploy:
    image: ubuntu:latest
    stage: deploy
    tags:
        - deployment
    script:
        - chmod og= $ID_RSA
        - apt update && apt install openssh-client -y
        - scp -i $ID_RSA -o StrictHostKeyChecking=no docker-compose.yml $SERVER_USER@$SERVER_IP:/srv/evac-sim
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /srv/portfolio &&
                                                                              docker pull $TAG_LATEST_EVAC_SIM &&
                                                                              docker-compose up --no-build -d"

    environment:
        name: production
        url: http://161.35.167.110
    only:
        - master